src/SmartRP/Controllers/KeywordsController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using SmartRP.Domain;
using SmartRP.Infrastructure;
using System;
using PagedList;
using SmartRP.Infrastructure.Data;
using SmartRP.Domain.Service;
using AutoMapper;
using System.Net;

namespace SmartRP.Controllers
{

	[Authorize]
	public class KeywordsController : Controller
	{

		#region Fields

		private readonly IWriteEntities _entities;
		private readonly IStudentService _studentServices;
		private readonly ISupervisorService _supervisorServices;
		private readonly ICoordinatorService _coordinatorServices;
		private readonly IUserService _userServices;
		private readonly ICommonService _commonServices;
		private readonly DbData _dbData;
		private readonly IProjectService _projectServices;
		private const int PageSize = 10;
		private readonly IMapper _mapper;

		#endregion

		#region Ctor

		public KeywordsController(IWriteEntities entities, IStudentService studentServices, ISupervisorService supervisorServices, ICoordinatorService coordinatorServices, IUserService userServices, ICommonService commonServices, DbData dbData, IProjectService projectServices, IMapper mapper)
		{
			_entities = entities;
			_studentServices = studentServices;
			_supervisorServices = supervisorServices;
			_coordinatorServices = coordinatorServices;
			_userServices = userServices;
			_commonServices = commonServices;
			_dbData = dbData;
			_projectServices = projectServices;
			_mapper = mapper;
		}

		#endregion

		[HttpGet]
		[Authorize(Roles = "Coordinator")]
		public ActionResult MyList(string currentFilter, string searchString, int? page)
		{
			if (searchString != null)
				page = 1;
			else
				searchString = currentFilter;
			ViewBag.CurrentFilter = searchString;
			int pageIndex = 1;
			pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;

			var keywordsVM = new List<KeywordViewModel>();
			Coordinator currentCoordinator = this.GetLoggedInUser() as Coordinator;
			var keywords = currentCoordinator.GetKeywords();
			keywords.ToList().ForEach(j =>
			{
				var vm = _mapper.Map<Keyword, KeywordViewModel>(j);
				keywordsVM.Add(vm);
			});

			ViewBag.UserId = _userServices.GetUserIDByEmail(User.Identity.Name).ID;
			ViewBag.TypeOfUser = _userServices.GetCurrentRole(User.Identity.Name);
			int pageNumber = (page ?? 1);
			return View(keywordsVM.ToPagedList(pageNumber, PageSize));
		}

		// GET: Keyword
		[HttpGet]
		[Authorize(Roles = "Coordinator")]
		public ViewResult Index(string sortOrder, string currentFilter, string searchString, int? page)
		{
			ViewBag.CurrentSort = sortOrder;
			ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
			ViewBag.DescriptionSortParm = sortOrder ==
												 "description" ? "descriptionDesc" : "description";
			if (searchString != null)
				page = 1;
			else
				searchString = currentFilter;

			ViewBag.CurrentFilter = searchString;
			int pageIndex = 1;
			pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;

			IEnumerable<Keyword> keywords = _commonServices.GetKeywordList();

			if (!String.IsNullOrEmpty(searchString))
			{
				keywords = keywords.Where(s => s.Description != null);
				keywords = keywords.Where(s => s.Title.ToLower().Contains(searchString.ToLower())
																|| s.Description.ToLower().Contains(searchString.ToLower()));
			}

			switch (sortOrder)
			{
				case "name_desc":
					keywords = keywords.OrderByDescending(s => s.Title);
					break;
				case "description":
					keywords = keywords.OrderBy(s => s.Description).ToPagedList(pageIndex, PageSize);
					break;
				case "descriptionDesc":
					keywords = keywords.OrderByDescending(s => s.Description).ToPagedList(pageIndex, PageSize);
					break;
				default:  // Name ascending 
					keywords = keywords.OrderBy(s => s.Title);
					break;
			}

			var interestVM = new List<KeywordViewModel>();
			keywords.ToList().ForEach(j =>
			{
				var vm = _mapper.Map<Keyword, KeywordViewModel>(j);
				interestVM.Add(vm);
			});

			ViewBag.TypeOfUser = _userServices.GetCurrentRole(User.Identity.Name);
			ViewBag.UserId = _userServices.GetUserIDByEmail(User.Identity.Name).ID;

			int pageNumber = (page ?? 1);
			return View(interestVM.ToPagedList(pageNumber, PageSize));
		}

		// GET: Keywords/Create
		public ActionResult Create()
		{
			KeywordViewModel model = new KeywordViewModel();
			string userType = _userServices.GetCurrentRole(User.Identity.Name);
			ViewBag.TypeOfUser = userType;
			if (userType != "Coordinator")
				return RedirectToAction("MyAccount/", userType);
			return View(model);
		}

		// POST: Keywords/Create
		[HttpPost]   //, Route("keywords/create")
		[ValidateAntiForgeryToken]
		[Authorize(Roles = "Coordinator")]
		public ActionResult Create(KeywordViewModel model)
		{
			string userType = _userServices.GetCurrentRole(User.Identity.Name);
			Coordinator currentCoordinator = this.GetLoggedInUser() as Coordinator;
			if (currentCoordinator == null || userType != "Coordinator")
				return RedirectToAction("MyAccount/", userType);

			if (ModelState.IsValid)
			{
				var keyword = _coordinatorServices.AddKeyword(currentCoordinator, model);

				if (keyword == null)
				{
					ViewBag.Error = "Error: Added Keyword has exist !";
					return View(model);
				}
			}
			return RedirectToAction("MyList");
		}

		// GET: Keywords/Edit/5
		[Authorize(Roles = "Coordinator")]
		public ActionResult Edit(int? id)
		{
			if (id == null)
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

			string userType = _userServices.GetCurrentRole(User.Identity.Name);
			ViewBag.TypeOfUser = userType;
			Coordinator currentCoordinator = this.GetLoggedInUser() as Coordinator;
			if (currentCoordinator == null || userType != "Coordinator")
				return RedirectToAction("MyAccount/", userType);
			var keyword = currentCoordinator.GetKeywordByID((int)id);
			var vm = _mapper.Map<Keyword, KeywordViewModel>(keyword);
			return View(vm);
		}

		// POST: Keyword/Edit/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Edit(KeywordViewModel model)
		{
			string userType = _userServices.GetCurrentRole(User.Identity.Name);
			Coordinator currentCoordinator = this.GetLoggedInUser() as Coordinator;
			if (currentCoordinator == null || userType != "Coordinator")
				return RedirectToAction("MyAccount/", userType);

			if (ModelState.IsValid && currentCoordinator.ID == model.CoordinatorID)
			{
				var keyword = _coordinatorServices.UpdateKeyword(currentCoordinator, model);
				if (keyword == null)
				{
					ViewBag.Error = "This Keyword does not existed!";
					return View(model);
				}
				return RedirectToAction("mylist");
			}
			return View(model);
		}

		// GET: Keywords/Delete/5
		[Authorize(Roles = "Coordinator")]
		public ActionResult Delete(int? id)
		{
			if (id == null)
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

			string userType = _userServices.GetCurrentRole(User.Identity.Name);
			ViewBag.TypeOfUser = userType;
			Coordinator currentCoordinator = this.GetLoggedInUser() as Coordinator;
			if (currentCoordinator == null || userType != "Coordinator")
				return RedirectToAction("MyAccount/", userType);
			var keyword = currentCoordinator.GetKeywordByID((int)id);

			int userUsedKeyword = _coordinatorServices.GetUserSelectedKeywordsCount(keyword.ID);
			int projectUsedKeyword = _coordinatorServices.GetProjectSelectedKeywordsCount(keyword.ID);

			if (userUsedKeyword != 0 || projectUsedKeyword != 0)
				return RedirectToAction("ErrorAlert", "Error", new
				{
					errorTitle = "Delete keyword error !",
					errorContent = "There are " + userUsedKeyword + " users has selected the keyword in the profile. \n\n" +
													"There are " + userUsedKeyword + " projects has selected the keyword"
				});


			var vm = _mapper.Map<Keyword, KeywordViewModel>(keyword);
			return View(vm);
		}

		// POST: Keyword/Delete/5
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public ActionResult DeleteConfirmed(int id)
		{
			string userType = _userServices.GetCurrentRole(User.Identity.Name);
			Coordinator currentCoordinator = this.GetLoggedInUser() as Coordinator;
			if (currentCoordinator == null || userType != "Coordinator")
				return RedirectToAction("MyAccount/", userType);

			ViewBag.TypeOfUser = userType;

			var keyword = _coordinatorServices.DeleteKeyword(currentCoordinator.ID, id);
			if (keyword == null)
			{
				ViewBag.Error = "This Keyword does not existed!";
				return RedirectToAction("delete", id);
			}
			return RedirectToAction("mylist");
		}

		//[HttpGet]
		//public ActionResult MatchInterest(string currentFilter, string searchString, int? page, string index)
		//{
		//	int PageSize = 20;
		//	if (searchString != null)
		//		page = 1;
		//	else
		//		searchString = currentFilter;

		//	ViewBag.CurrentFilter = searchString;
		//	int pageIndex = 1;
		//	pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;

		//	var userType = this._userServices.GetCurrentRole(User.Identity.Name);
		//	ViewBag.TypeOfUser = userType;
		//	ViewBag.EnrollSemester = this._commonServices.IsEnrolledUser(User.Identity.Name);
		//	int userId = 0;
		//	switch (userType)
		//	{
		//		case "Student":
		//			var student = this._studentServices.GetLoggedInStudent();
		//			if (student == null)
		//				return RedirectToAction("ErrorAlert", "Error", new { errorTitle = "User error", errorContent = "Can not found student !" });
		//			userId = student.ID;
		//			break;
		//		case "Supervisor":
		//			var supervisor = this._supervisorServices.GetLoggedInSupervisor();
		//			if (supervisor == null)
		//				return RedirectToAction("ErrorAlert", "Error", new { errorTitle = "User error", errorContent = "Can not found supervisor !" });
		//			userId = supervisor.ID;
		//			break;
		//		case "Coordinator":
		//			var coordinator = this._coordinatorServices.GetLoggedInCoordinator();
		//			if (coordinator == null)

src/SmartRP/Views/Keywords/Create.cshtml
@model SmartRP.Domain.KeywordViewModel

@{
	ViewBag.Title = "Create Interest Keywords";
}

<div class="container-fluid">
	<div class="row">
		<div class="col-sm-3 col-md-2 sidebar">
			<h3>@ViewBag.TypeOfUser</h3>
			@Html.Action("Menu", (string)@ViewBag.TypeOfUser)

		</div>
		<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
			<p class="bg-light" style="padding-top:8px;">
				&nbsp; <span class="glyphicon glyphicon-home"></span>
				&nbsp; <span class="fa fa-angle-right"></span>&nbsp;
				@Html.ActionLink(" Manage Keyword", "manage-keywords", (string)@ViewBag.TypeOfUser, null, null)
				&nbsp; <span class="fa fa-angle-right"></span>&nbsp;
				Add New Keyword
			</p>
			<div class="alert alert-success alert-dismissable fade in">
				<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
				<strong>Information: </strong>When you add a new keyword, please give a brief explanation about the keyword, you may use the definition from the Wikipedia or a scientific dictionary.
			</div>
			<hr />
			@using (Html.BeginForm())
			{
			@Html.AntiForgeryToken()

				<div class="form-horizontal">

					@Html.ValidationSummary(true, "", new { @class = "text-danger" })

					<div class="form-group" hidden="hidden">
						@Html.LabelFor(model => model.ID, htmlAttributes: new { @class = "control-label col-md-2" })
						<div class="col-md-10">
							@Html.EditorFor(model => model.ID, new { htmlAttributes = new { @class = "form-control" } })
							@Html.ValidationMessageFor(model => model.ID, "", new { @class = "text-danger" })
						</div>
					</div>

					<div class="form-group">
						@Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
						<div class="col-md-10">
							@Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
							@Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
						</div>
					</div>

					<div class="form-group">
						@Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
						<div class="col-md-10">
							@Html.TextAreaFor(model => model.Description, new { @class = "form-control", @rows = "5", required = "required" })
							@Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
						</div>
					</div>

					@{if (ViewBag.Error != null)
						{
						<div class="alert alert-danger">
							<strong>Danger! @ViewBag.Error</strong>
						</div>
						}
					}

					<div class="form-group">
						<div class="col-md-offset-2 col-md-10">
							<input type="submit" value="Add" class="btn btn-success" />
						</div>
					</div>
				</div>
						}
 
		</div>
	</div>
</div>

src/SmartRP/Views/Keywords/Delete.cshtml
@model SmartRP.Domain.KeywordViewModel

@{
    ViewBag.Title = "Delete";
}

<p class="bg-light" style="padding-top:8px;">
	&nbsp; <span class="glyphicon glyphicon-home"></span>
	&nbsp; <span class="fa fa-angle-right"></span>&nbsp;
	Manage Keyword
	&nbsp; <span class="fa fa-angle-right"></span>&nbsp;
	Delete
</p>

<h3>Delete</h3>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Interest Keyword</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
 
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-success" /> |
            @Html.ActionLink("Back to List", "mylist")
        </div>
    }
</div>

src/SmartRP/Views/Keywords/Details.cshtml
@model SmartRP.Domain.KeywordViewModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Interest</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

src/SmartRP/Views/Keywords/Edit.cshtml
@model SmartRP.Domain.KeywordViewModel

@{
	ViewBag.Title = "Edit Keyword";
}

<div class="container-fluid">
	<div class="row">
		<div class="col-sm-3 col-md-2 sidebar">
			<br />
			<h4>@ViewBag.TypeOfUser</h4>
			@Html.Action("Menu", (string)@ViewBag.TypeOfUser)
		</div>
		<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
			<p class="bg-light" style="padding-top:8px;">
				&nbsp; <span class="glyphicon glyphicon-home"></span>
				&nbsp; <span class="fa fa-angle-right"></span>&nbsp;
				@Html.ActionLink(" Manage Keyword", "manage-keywords", (string)@ViewBag.TypeOfUser, null, null)
				&nbsp; <span class="fa fa-angle-right"></span>&nbsp;
				@Html.ActionLink(" Added keyword by me", "mylist", "keywords", null, null)
				&nbsp; <span class="fa fa-angle-right"></span>&nbsp;
				Edit Keyword
			</p>
			<div class="alert alert-success alert-dismissable fade in">
				<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
				<strong>Information: </strong> In this page, you can edit the keywords
			</div>
			<hr />
			@using (Html.BeginForm())
			{
			@Html.AntiForgeryToken()

				@Html.ValidationSummary(true, "", new { @class = "text-danger" })
				@Html.HiddenFor(model => model.ID)
				@Html.HiddenFor(model => model.CoordinatorID)
				<div class="form-group" hidden="hidden">
					@Html.LabelFor(model => model.ID, htmlAttributes: new { @class = "control-label col-md-2" })
					<div class="col-md-10">
						@Html.EditorFor(model => model.ID, new { htmlAttributes = new { @class = "form-control" } })
						@Html.ValidationMessageFor(model => model.ID, "", new { @class = "text-danger" })
					</div>
				</div>

				<div class="form-group">
					@Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
					<div class="col-md-10">
						@Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
						@Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
					</div>
				</div>

					<div class="form-group">
						@Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
						<div class="col-md-10">
							@Html.TextAreaFor(model => model.Description, new { @class = "form-control", @rows = "5" })
							@Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
						</div>
					</div>

				if (ViewBag.Error != null)
				{
				<div class="alert alert-danger">
					<strong>Danger! @ViewBag.Error</strong>
				</div>
				}

				<div class="form-group">
					<div class="col-md-offset-2 col-md-10">
						<br />
						<input type="submit" value="Save" class="btn btn-success" />

						<button onclick="goBack()" class="btn btn-default">Go Back</button>
						<script>
							function goBack() {
								window.history.back();
							}
						</script>
					</div>
				</div>
			}
		</div>
	</div>
</div>

src/SmartRP/Views/Keywords/Index.cshtml
@model PagedList.IPagedList<SmartRP.Domain.KeywordViewModel>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
	ViewBag.Title = "List";
}

<div class="container-fluid">
	<div class="row">
		<div class="col-sm-3 col-md-2 sidebar">
			<br />
			<h4>@ViewBag.TypeOfUser</h4>
			@Html.Action("Menu", (string)@ViewBag.TypeOfUser)

		</div>
		<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
			<p class="bg-light" style="padding-top:8px;">
				&nbsp; <span class="glyphicon glyphicon-home"></span>
				&nbsp; <span class="fa fa-angle-right"></span>&nbsp;
				@Html.ActionLink(" Manage Keyword", "manage-keywords", (string)@ViewBag.TypeOfUser, null, null)
			</p>
			<div class="alert alert-success alert-dismissable fade in">
				<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
				<strong>Information: </strong>These keywords will be selected in user profile and project that use by the “Match Keywords” function to find others who share similar research interests to the user.
			</div>
			@if (ViewBag.TypeOfUser == "Coordinator")
			{
			<p>
				@Html.ActionLink(" Add a new keyword", "Create", "Keywords", null, htmlAttributes: new { title = "Add Interest Keyword", @class = "fa fa-plus-circle btn btn-warning btn-sm" })
				@Html.ActionLink(" Added keyword by me", "mylist", "Keywords", null, htmlAttributes: new { title = "My Added Keyword", @class = "fa fa-heart-o btn btn-success btn-sm" })
			</p>
			}

			@using (Html.BeginForm("Index", "Keywords", FormMethod.Get))
			{
			<p>
				@Html.TextBox("SearchString", ViewBag.CurrentFilter as string, new { @placeholder = "Search for Title or Description", @style = "width:300px" })
				<button type="submit" value="Search" class="btn btn-normal btn-sm"> <span class="fa fa-search" aria-hidden="true"></span> Search </button>

			</p>
			}
			<table class="table table-striped">
				<tr>
					<th>
						@Html.ActionLink("Title ", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })<span class="fa fa-arrows-v" aria-hidden="true"> </span>
					</th>

					<th>
						@Html.ActionLink("Description ", "Index", new { sortOrder = ViewBag.DescriptionSortParm, currentFilter = ViewBag.CurrentFilter })<span class="fa fa-arrows-v" aria-hidden="true"> </span>
					</th>
					<th>
						Owner
					</th>
					@*<th></th>*@
				</tr>

				@foreach (var item in Model)
				{
				<tr>
					<td>
						@Html.DisplayFor(modelItem => item.Title)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.Description)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.CoordinatorID)
					</td>
				</tr>
				}
			</table>

			<br />
			Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

			@Html.PagedListPager(Model, page => Url.Action("Index",
		new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))

		</div>
	</div>
</div>

src/SmartRP/Views/Keywords/MyList.cshtml
@model  PagedList.IPagedList<SmartRP.Domain.KeywordViewModel>
@using PagedList.Mvc;
@{
	ViewBag.Title = "my list";
}

<div class="container-fluid">
	<div class="row">
		<div class="col-sm-3 col-md-2 sidebar">
			<h3>@ViewBag.TypeOfUser</h3>
			@Html.Action("Menu", (string)@ViewBag.TypeOfUser)

		</div>
		<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
			<p class="bg-light" style="padding-top:8px;">
				&nbsp; <span class="glyphicon glyphicon-home"></span>
				&nbsp; <span class="fa fa-angle-right"></span>&nbsp;
				@Html.ActionLink(" Manage Keyword", "manage-keywords", (string)@ViewBag.TypeOfUser, null, null)
				&nbsp; <span class="fa fa-angle-right"></span>&nbsp;
				@Html.ActionLink(" Added keyword by me", "mylist", "keywords", null, null)
			</p>

			<div class="alert alert-success alert-dismissable fade in">
				<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
				<strong>Information: </strong> In this page, you can edit or delete the keyword, but if the keyword has been selected by other users, you can't delete it.
			</div>
			@Html.ActionLink(" Add New Keyword", "Create", "Keywords", null, htmlAttributes: new { title = "Add Interest Keyword", @class = "fa fa-plus-circle btn btn-warning btn-sm" })
			<span> </span>
			@Html.ActionLink(" All Keyword", "Index", "Keywords", null, htmlAttributes: new { title = "All Interest Keyword", @class = "fa fa-bars btn btn-info btn-sm" })
			<br /><br />
			<table class="table table-striped">
				<tr>
					<th>
						@Html.DisplayNameFor(model => model.FirstOrDefault().Title)
					</th>
					<th>
						@Html.DisplayNameFor(model => model.FirstOrDefault().Description)
					</th>

					<th>Action</th>
				</tr>

				@foreach (var item in Model)
				{
				<tr>
					<td>
						@Html.DisplayFor(modelItem => item.Title)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.Description)
					</td>

					<td>
						@{
							if (ViewBag.UserId == item.CoordinatorID)
							{
							@Html.ActionLink("Edit", "Edit", new { id = item.ID })
								@:| @Html.ActionLink("Delete", "Delete", new { id = item.ID })
								 }
						}

					</td>
				</tr>
				}

			</table>
 

			<br />
			Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

			@Html.PagedListPager(Model, page => Url.Action("mylist",
		new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
		</div>
	</div>
</div>