src/SmartRP/Controllers/TermsController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using SmartRP.Domain;
using SmartRP.Domain.Service;
using AutoMapper;
using System;
using PagedList;

namespace SmartRP.Controllers
{

	[Authorize(Roles = "Coordinator")]
	public class TermsController : Controller
	{

		#region Fields

		private readonly ICoordinatorService _coordinatorServices;
		private readonly IUserService _userServices;
		private readonly ICommonService _commonServices;
		private readonly IMapper _mapper;
		private const int PageSize = 10;

		#endregion

		#region Ctor

		public TermsController(ICoordinatorService coordinatorServices, IUserService userServices, ICommonService commonServices, IMapper mapper)
		{
			_coordinatorServices = coordinatorServices;
			_userServices = userServices;
			_commonServices = commonServices;
			_mapper = mapper;
		}

		#endregion

		#region Action

		public ActionResult Index()
		{
			Coordinator currentCoordinator = this.GetLoggedInUser() as Coordinator;
			TermViewModel model = new TermViewModel();
			List<TermViewModel> termVM = new List<TermViewModel>();
			if (currentCoordinator != null)
			{
				ViewBag.CoordinatorID = currentCoordinator.ID;
				var terms = _commonServices.GetTermList().OrderByDescending(a => a.StartAt).ToList();
				terms.ForEach(j =>
				{
					var vm = _mapper.Map<Term, TermViewModel>(j);
					termVM.Add(vm);
				});
			}
			ViewBag.CoordinatorID = currentCoordinator.ID;
			ViewBag.TypeOfUser = _userServices.GetCurrentRole(User.Identity.Name);
			return View(termVM);
		}

		// GET: Terms/Create
		public ActionResult Create()
		{
			Coordinator currentCoordinator = this.GetLoggedInUser() as Coordinator;
			TermEditModel model = _mapper.Map<Term, TermEditModel>(new Term(currentCoordinator.ID));
			ViewBag.TypeOfUser = _userServices.GetCurrentRole(User.Identity.Name);
			return View(model);
		}

		// POST: Terms/Create
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Create(TermEditModel model)
		{
			Coordinator currentCoordinator = this.GetLoggedInUser() as Coordinator;
			if (currentCoordinator != null && ModelState.IsValid)
				_coordinatorServices.AddTerm(currentCoordinator, model);

			return RedirectToAction("Index");
		}

		// GET: Terms/Edit/5
		public ActionResult Edit(int? id)
		{
			ViewBag.TypeOfUser = _userServices.GetCurrentRole(User.Identity.Name);
			Coordinator currentCoordinator = this.GetLoggedInUser() as Coordinator;
			if (currentCoordinator == null || id == null)
				return RedirectToAction("Index");
			Term term = currentCoordinator.GetTerm((int)id);
			if (term == null)
				return RedirectToAction("Index");
			TermEditModel model = _mapper.Map<Term, TermEditModel>(term);
			return View(model);
		}

		// POST: Terms/Edit/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Edit(TermEditModel model)
		{
			Coordinator currentCoordinator = this.GetLoggedInUser() as Coordinator;
			if (currentCoordinator != null && ModelState.IsValid && model.CoordinatorID == currentCoordinator.ID)
			{
				_coordinatorServices.UpdateTerm(currentCoordinator, model);
				return RedirectToAction("Index");
			}
			return View(model);
		}

		// GET: Terms/Delete/5
		public ActionResult Delete(int? id)
		{
			Coordinator currentCoordinator = this.GetLoggedInUser() as Coordinator;
			if (id == null || currentCoordinator == null)
				return RedirectToAction("Index");
			Term term = currentCoordinator.GetTerm((int)id);
			if (term == null)
				return RedirectToAction("Index");
			TermViewModel model = _mapper.Map<Term, TermViewModel>(term);
			var enrolledStudents = _commonServices.GetEnrolledStudentsBySemester(term);

      //need to count co-supervisor and ext-supervisor 
			if (enrolledStudents.Count() != 0)
				return RedirectToAction("ErrorAlert", "Error", new
				{
					errorTitle = "Delete semester error !",
					errorContent = "There are " + enrolledStudents.Count() + " students has enrolled the semester."
				});
			ViewBag.TypeOfUser = _userServices.GetCurrentRole(User.Identity.Name);
			return View(model);
		}

		// POST: Terms/Delete/5
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public ActionResult DeleteConfirmed(int id)
		{
			Coordinator currentCoordinator = this.GetLoggedInUser() as Coordinator;
			if (currentCoordinator != null)
				_coordinatorServices.DeleteTerm(currentCoordinator, id);

			return RedirectToAction("Index");
		}

		#endregion

		#region Enrol

		[HttpGet, Route("terms/enrolled-students")]
		public ActionResult EnrolledStudents(int? id, string currentFilter, string searchString, int? page)
		{
			if (searchString != null)
				page = 1;
			else
				searchString = currentFilter;

			ViewBag.CurrentFilter = searchString;
			int pageIndex = 1;
			pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;

			ViewBag.SubjectID = id;
			ViewBag.SubjectName = _commonServices.GetSemesterBySubjectID((int)id).TermName +" "+ _commonServices.GetSubjectNameByID((int)id);
			var students =_commonServices.GetCurrentSubjectStudents((int)id).ToList();

			if (!String.IsNullOrEmpty(searchString))
			{
				students = students.Where(s => s.Firstname.ToLower().Contains(searchString.ToLower()) ||
								s.Lastname.ToLower().Contains(searchString.ToLower()) ||
								s.StudentID.ToLower().Contains(searchString.ToLower()) ||
								s.Email.ToLower().Contains(searchString.ToLower())).ToList();
			}

			var studentVMList = new List<StudentViewModel>();
			if (students != null)
			{
				students.ForEach(j =>
				{
					var vm = _mapper.Map<Student, StudentViewModel>(j); 
					studentVMList.Add(vm);
				});
			}

			string userType = _userServices.GetCurrentRole(User.Identity.Name);
			ViewBag.TypeOfUser = userType;
			int pageNumber = (page ?? 1);
			return View(studentVMList.ToPagedList(pageNumber, PageSize));
		}


		#endregion
	}
}

src/SmartRP/Views/Terms/Create.cshtml
@model SmartRP.Domain.TermEditModel
@using SmartRP.Domain
@{
	ViewBag.Title = "Create";
}

<script src="@Url.Content("~/Scripts/Shared/datepicker.js")" type="text/javascript"></script>
<div class="container-fluid">
	<div class="row">
		<div class="col-sm-3 col-md-2 sidebar">
			<br />
			<h4>@ViewBag.TypeOfUser</h4>
			@Html.Action("Menu", (string)@ViewBag.TypeOfUser)

		</div>
		<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
			<p class="bg-light" style="padding-top:8px;">
				&nbsp; <span class="glyphicon glyphicon-home"></span>
				&nbsp; <span class="fa fa-angle-right"></span>&nbsp;
				@Html.ActionLink(" Manage Semester", "manage-semester", (string)@ViewBag.TypeOfUser, null, null)
			</p>
			<div class="alert alert-success alert-dismissable fade in">
				<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
				<strong>Information:</strong> Add a new semester!
			</div>
			@using (Html.BeginForm())
			{
			@Html.AntiForgeryToken()
				@Html.HiddenFor(model => model.CoordinatorID)
				<div class="form-horizontal">
					@Html.ValidationSummary(true, "", new { @class = "text-danger" })
					<div class="form-group">
						@Html.LabelFor(model => model.Year, htmlAttributes: new { @class = "control-label col-md-2" })
						<div class="col-md-10">
							@{
								var currentYear = DateTime.Now.Year;
							}
							@Html.DropDownListFor(m => m.Year,
								new SelectList(
									new List<Object>{
											 new { value = @currentYear , text = @currentYear},
											 new { value = @currentYear+1 , text = @currentYear+1},
										}, "value", "text", 0), new { @class = "form-control" })
							@Html.ValidationMessageFor(model => model.Year, "", new { @class = "text-danger" })

						</div>
					</div>

					<div class="form-group">
						@Html.LabelFor(model => model.Session, htmlAttributes: new { @class = "control-label col-md-2" })
						<div class="col-md-10">
							@Html.DropDownListFor(model => model.Session, new SelectList(Enum.GetValues(typeof(Session))), new { @class = "form-control" })
							@Html.ValidationMessageFor(model => model.Session, "", new { @class = "text-danger" })
						</div>
					</div>

					<div class="form-group">
						@Html.LabelFor(model => model.CheckBoxSubjectNames, htmlAttributes: new { @class = "control-label col-md-2" })
						<div class="col-md-10">
							<div class="alert alert-warning" role="alert" style="overflow:auto; max-height:200px">
								@for (int i = 0; i < Model.CheckBoxSubjectNames.Count; i++)
								{
								<table>
									<tr>
										<th style="width:120px">@Html.DisplayFor(m => m.CheckBoxSubjectNames[i].SubjectName)</th>
										<th>@Html.CheckBoxFor(m => m.CheckBoxSubjectNames[i].IsSelected, htmlAttributes: new { @style = "cursor:pointer;zoom:1.2;" })</th>
										@Html.HiddenFor(m => m.CheckBoxSubjectNames[i].SubjectName)
									</tr>

								</table>
								}
							</div>
							@Html.ValidationMessageFor(model => model.EndAt, "", new { @class = "text-danger" })
						</div>
					</div>


					<div class="form-group">
						<div class="col-md-offset-2 col-md-10">
							<input type="submit" value="Create" class="btn btn-success" />
						</div>
					</div>
				</div>

				@Html.ActionLink("Back to List", "Index")
			}

		</div>
	</div>
</div>

src/SmartRP/Views/Terms/Delete.cshtml
@model SmartRP.Domain.TermViewModel

@{
	ViewBag.Title = "Delete";
}
<div class="container-fluid">
	<div class="row">
		<div class="col-sm-3 col-md-2 sidebar">
			<br />
			<h4>@ViewBag.TypeOfUser</h4>
			@Html.Action("Menu", (string)@ViewBag.TypeOfUser)

		</div>
		<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
			<p class="bg-light" style="padding-top:8px;">
				&nbsp; <span class="glyphicon glyphicon-home"></span>
				&nbsp; <span class="fa fa-angle-right"></span>&nbsp;
				@Html.ActionLink(" Manage Semester", "manage-semester", (string)@ViewBag.TypeOfUser, null, null)
				&nbsp; <span class="fa fa-angle-right"></span>&nbsp;
				Delete
			</p>
			<h3>Are you sure you want to delete this?</h3>
			<div>
			 
				<hr />
				<dl class="dl-horizontal">
					<dt>
						@Html.DisplayNameFor(model => model.TermName)
					</dt>
					<dd>
						@Html.DisplayFor(model => model.TermName)
					</dd>
					<dt>
						@Html.DisplayNameFor(model => model.Subjects)
					</dt>
					<dd>
						@foreach (var subject in Model.Subjects)
						{
						<span style="color:#22be10; font-size:smaller"> @subject.SubjectName </span><br />
						}
					</dd>
					<dt>
						@Html.DisplayNameFor(model => model.StartAt)
					</dt>

					<dd>
						@Html.DisplayFor(model => model.StartAt)
					</dd>

					<dt>
						@Html.DisplayNameFor(model => model.EndAt)
					</dt>

					<dd>
						@Html.DisplayFor(model => model.EndAt)
					</dd>

					<dt>
						@Html.DisplayNameFor(model => model.CoordinatorID)
					</dt>

					<dd>
						@Html.DisplayFor(model => model.CoordinatorID)
					</dd>

				</dl>

				@using (Html.BeginForm())
				{
				@Html.AntiForgeryToken()

					<div class="form-actions no-color">
						<input type="submit" value="Delete" class="btn btn-success" /> |
						@Html.ActionLink("Back to List", "Index")
					</div>
				}
			</div>
		</div>
	</div>
</div>

src/SmartRP/Views/Terms/Edit.cshtml
@model SmartRP.Domain.TermEditModel

@{
	ViewBag.Title = "Edit";
}

<script src="@Url.Content("~/Scripts/Shared/datepicker.js")" type="text/javascript"></script>

<div class="container-fluid">
	<div class="row">
		<div class="col-sm-3 col-md-2 sidebar">
			<br />
			<h4>@ViewBag.TypeOfUser</h4>
			@Html.Action("Menu", (string)@ViewBag.TypeOfUser)

		</div>
		<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
			<p class="bg-light" style="padding-top:8px;">
				&nbsp; <span class="glyphicon glyphicon-home"></span>
				&nbsp; <span class="fa fa-angle-right"></span>&nbsp;
				@Html.ActionLink(" Manage Semester", "manage-semester", (string)@ViewBag.TypeOfUser, null, null)
				&nbsp; <span class="fa fa-angle-right"></span>&nbsp;
				Edit
			</p>
			<div class="alert alert-success alert-dismissable fade in">
				<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
				<strong>Information: </strong> In this page, you can edit semester
			</div>
	 
			@using (Html.BeginForm())
			{
			@Html.AntiForgeryToken()

				<div class="form-horizontal">

					@Html.ValidationSummary(true, "", new { @class = "text-danger" })
					@Html.HiddenFor(model => model.ID)
					@Html.HiddenFor(model => model.CoordinatorID)
					<div class="form-group">
						@Html.LabelFor(model => model.TermName, htmlAttributes: new { @class = "control-label col-md-2" })
						<div class="col-md-10">
							@Html.EditorFor(model => model.TermName, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
							@Html.ValidationMessageFor(model => model.TermName, "", new { @class = "text-danger" })
						</div>
					</div>
					<div class="form-group">
						@Html.LabelFor(model => model.StartAt, htmlAttributes: new { @class = "control-label col-md-2" })
						<div class="col-md-10">
							<div class='input-group date datetimepicker'>
								@Html.EditorFor(model => model.StartAt, new { htmlAttributes = new { @class = "form-control", @placeholder = "DD/MM/YYYY" } })
								<span class="input-group-addon">
									<span class="glyphicon glyphicon-calendar"></span>
								</span>
							</div>
							@Html.ValidationMessageFor(model => model.StartAt, "", new { @class = "text-danger" })
						</div>
					</div>
					<div class="form-group">
						@Html.LabelFor(model => model.EndAt, htmlAttributes: new { @class = "control-label col-md-2" })
						<div class="col-md-10">
							<div class='input-group date datetimepicker'>
								@Html.EditorFor(model => model.EndAt, new { htmlAttributes = new { @class = "form-control", @placeholder = "DD/MM/YYYY" } })
								<span class="input-group-addon">
									<span class="glyphicon glyphicon-calendar"></span>
								</span>
							</div>
							@Html.ValidationMessageFor(model => model.EndAt, "", new { @class = "text-danger" })
						</div>
					</div>

					<div class="form-group">
						@Html.LabelFor(model => model.CheckBoxSubjectNames, htmlAttributes: new { @class = "control-label col-md-2" })
						<div class="col-md-10">
							<div class="alert alert-warning" role="alert" style="overflow:auto; max-height:200px">
								@for (int i = 0; i < Model.CheckBoxSubjectNames.Count; i++)
								{
								<table>
									<tr>
										<th style="width:120px">@Html.DisplayFor(m => m.CheckBoxSubjectNames[i].SubjectName)</th>
										<th>@Html.CheckBoxFor(m => m.CheckBoxSubjectNames[i].IsSelected, htmlAttributes: new { @style = "cursor:pointer;zoom:1.2;" })</th>
										@Html.HiddenFor(m => m.CheckBoxSubjectNames[i].SubjectName)
									</tr>
								</table>
								}
							</div>
							@Html.ValidationMessageFor(model => model.EndAt, "", new { @class = "text-danger" })
						</div>
					</div>

					<div class="form-group">
						<div class="col-md-offset-2 col-md-10">
							<input type="submit" value="Save" class="btn btn-success" />
							<button onclick="goBack()" class="btn btn-default">Go Back</button>
							<script>
							function goBack() {
								window.history.back();
							}
							</script>
						</div>
					</div>
				</div>
			}
 
		</div>
	</div>
</div>

src/SmartRP/Views/Terms/EnroledTermList.cshtml
@model IEnumerable<SmartRP.Domain.EnrolTermViewModel>

@{
	ViewBag.Title = "EnroledTermList";
}
<div class="container-fluid">
	<div class="row">
		<div class="col-sm-3 col-md-2 sidebar">
			<br />
			<h4>@ViewBag.TypeOfUser</h4>
			@Html.Action("Menu", (string)@ViewBag.TypeOfUser)
		</div>
		<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
			@*<h2>My Enroled Semester List</h2>*@
			<br />
			<div class="alert alert-success alert-dismissable fade in">
				<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
				<strong>Information:</strong> You use this page to enroll into a semester. Pick up one from the existing semesters to enroll. This is essential for you to use other functions.
			</div>
			<p>
				@{
					if (!ViewBag.isEnrolledUser)
					{
					@Html.ActionLink(" Enrol a Term", "EnrolTerm", new { userId = ViewBag.userId }, new { @class = "fa fa-plus-circle btn btn-warning btn-sm" })
					}
				}
	
			</p>
			@{
				if (Model.Count() > 0)
				{
				<table class="table table-striped">
					<tr>
						<th>
							@Html.DisplayNameFor(model => model.TermName)
						</th>
						<th>
							@Html.DisplayNameFor(model => model.StartAt)
						</th>
						<th>
							@Html.DisplayNameFor(model => model.EndAt)
						</th>
						<th>
							@Html.DisplayNameFor(model => model.UserType)
						</th>
						<th></th>
					</tr>

					@foreach (var item in Model)
				{
				<tr>
					<td>
						@Html.DisplayFor(modelItem => item.TermName)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.StartAt)

					</td>
					<td>
						@Html.DisplayFor(modelItem => item.EndAt)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.UserType)
					</td>
				</tr>
				}
				</table>

				}
			}

		</div>
	</div>
</div>

src/SmartRP/Views/Terms/EnrolledStudents.cshtml
@model PagedList.IPagedList<SmartRP.Domain.StudentViewModel>
@using PagedList.Mvc;
@{
	ViewBag.Title = "Index";
}
<div class="container-fluid">
	<div class="row">
		<div class="col-sm-3 col-md-2 sidebar">
			<br />
			<h4>@ViewBag.TypeOfUser</h4>
			@Html.Action("Menu", (string)@ViewBag.TypeOfUser)

		</div>
		<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
			<p class="bg-light" style="padding-top:8px;">
				&nbsp; <span class="glyphicon glyphicon-home"></span>
				&nbsp; <span class="fa fa-angle-right"></span>&nbsp;
				
				@Html.ActionLink(" Manage Semester", "manage-semester", (string)@ViewBag.TypeOfUser, null, null)
				&nbsp; <span class="fa fa-angle-right"></span>&nbsp;
				Enrolled Students
			</p>
			<div class="alert alert-success alert-dismissable fade in">
				<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
				<strong>Information: </strong>Enrolled Students in @ViewBag.SubjectName
			</div>
			@using (Html.BeginForm("EnrolledStudents", "Terms", FormMethod.Get))
			{
			<p>
				<input type="hidden" name="id" value="@ViewBag.SubjectID" />
				@Html.TextBox("SearchString", ViewBag.CurrentFilter as string, new { @placeholder = "Search for Firstname or Lastname or Email or Student ID", @style = "width:450px" })
				<button type="submit" value="Search" class="btn btn-normal btn-sm"> <span class="fa fa-search" aria-hidden="true"></span> Search </button>
			</p>
			}
			<table class="table table-striped">
				<tr>
					<th>

						@Html.DisplayNameFor(model => model.FirstOrDefault().Firstname)
					</th>
					<th>
						@Html.DisplayNameFor(model => model.FirstOrDefault().Lastname)
					</th>
					<th>
						@Html.DisplayNameFor(model => model.FirstOrDefault().Email)
					</th>
					<th>
						@Html.DisplayNameFor(model => model.FirstOrDefault().StudentID)

					</th>
					<th>Profile</th>
					<th>
						@Html.DisplayNameFor(model => model.FirstOrDefault().HasJoinedCurrentSubjectProjectGroup)
					</th>
				</tr>

				@foreach (var item in Model)
				{
				<tr>
					<td>
						@Html.DisplayFor(modelItem => item.Firstname)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.Lastname)

					</td>
					<td>
 
						<a href="mailto:@Html.DisplayFor(modelItem => item.Email)">@Html.DisplayFor(modelItem => item.Email)</a>
          </td>
					<td>
						@Html.DisplayFor(modelItem => item.StudentID)
					</td>
					<td>
						@Html.ActionLink("Student #" + item.ID, "Profile", "Student", new { id = item.ID }, htmlAttributes: new { target = "_blank" })
					</td>
					<td>
						@if (item.HasJoinedCurrentSubjectProjectGroup)
						{ <span>Yes</span>}
						else
						{ <span>-</span>}

					</td>
				</tr>
				}

			</table>
			<br />
			Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

			@Html.PagedListPager(Model, page => Url.Action("EnrolledStudents",
		new {id= ViewBag.SubjectID, page, currentFilter = ViewBag.CurrentFilter }))


			<hr />
			<div class="col-md-12">
				<button onclick="goBack()" class="btn btn-default">Go Back</button>
				<script>
					function goBack() {
						window.history.back();
					}
				</script>
			</div>
		</div>
	</div>
</div>

src/SmartRP/Views/Terms/Index.cshtml
@model IEnumerable<SmartRP.Domain.TermViewModel>

@{
	ViewBag.Title = "Index";
}
<div class="container-fluid">
	<div class="row">
		<div class="col-sm-3 col-md-2 sidebar">
			<br />
			<h4>@ViewBag.TypeOfUser</h4>
 
			@Html.Action("Menu", (string)@ViewBag.TypeOfUser)
		</div>
		<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
			<p class="bg-light" style="padding-top:8px;">
				&nbsp; <span class="glyphicon glyphicon-home"></span>
				&nbsp; <span class="fa fa-angle-right"></span>&nbsp;
				@Html.ActionLink(" Manage Semester", "manage-semester", (string)@ViewBag.TypeOfUser, null, null)
			</p>

			<div class="alert alert-danger alert-dismissable fade in">
				<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
				<strong>Notice:</strong> Semester(Term) need to set first !
			</div>
			<p>

				@Html.ActionLink(" Add a new semester", "Create", "Terms", null, htmlAttributes: new { title = "Add New Term", @class = "fa fa-plus-circle btn btn-warning btn-sm" })
			</p>
			<table class="table table-striped">
				<tr>
					<th>
						@Html.DisplayNameFor(model => model.TermName)
					</th>
					<th>
						@Html.DisplayNameFor(model => model.StartAt)
					</th>
					<th>
						@Html.DisplayNameFor(model => model.EndAt)
					</th>
					<th>Opened Subject List</th>
					<th>Action</th>
				</tr>

				@foreach (var item in Model)
				{
				<tr>
					<td>
						@Html.DisplayFor(modelItem => item.TermName)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.StartAt)

					</td>
					<td>
						@Html.DisplayFor(modelItem => item.EndAt)
					</td>
					<td>
						@foreach (var subject in item.Subjects)
						{
						<span style="color:#14b11c; font-size:smaller"> @subject.SubjectName </span>
						@Html.ActionLink(" Enrolled Students", "EnrolledStudents", "Terms", new { id = subject.ID }, new { @class = "fa fa-users" })<br />
						}
 
					</td>
					<td>
		 
						@if (item.CoordinatorID == ViewBag.CoordinatorID)
						{
						  <span>| </span>	@Html.ActionLink(" Edit", "Edit", new { id = item.ID }, new { @class = "fa fa-pencil", @style = "color:orange" })
							<span> | </span>	@Html.ActionLink(" Delete", "Delete", new { id = item.ID }, new { @class = "fa fa-close", @style = "color:red" })<span> |</span>
						}
					</td>
				</tr>
				}

			</table>
		</div>
	</div>
</div>