src/SmartRP/Controllers/CoordinatorController.cs
using AutoMapper;
using SmartRP.Domain;
using SmartRP.Domain.Service;
using SmartRP.Infrastructure.Data;
using System.Collections.Generic;
using System.Web.Mvc;

namespace SmartRP.Controllers
{
	[Authorize]
	public class CoordinatorController : Controller
	{
		// GET: Coordinator

		#region Fields

		private readonly ICommonService _commonServices;
		private readonly IProjectService _projectServices;
		private readonly DbData _dbData;
		private readonly IMapper _mapper;

		#endregion

		#region Ctor

		public CoordinatorController(ICommonService commonServices, IProjectService projectServices, DbData dbData, IMapper mapper)
		{
			_commonServices = commonServices;
			_projectServices = projectServices;
			_dbData = dbData;
			_mapper = mapper;
		}

		#endregion

		#region Menu

		[Authorize(Roles = "Coordinator")]
		public ActionResult Menu()
		{
			return PartialView("CoordinatorMenu");
		}

		#endregion

		#region Profile

		[Authorize(Roles = "Coordinator")]
		public ActionResult MyAccount()
		{
			Coordinator currentCoordinator = this.GetLoggedInUser() as Coordinator;
			CoordinatorViewModel model = new CoordinatorViewModel();
			if (currentCoordinator != null)
			{
				model = _mapper.Map<Coordinator, CoordinatorViewModel>(currentCoordinator);
				model.UserSelectedKeywords = _commonServices.GetUserSelectedKeywordsByUserID(currentCoordinator.ID);
			}
			return View(model);
		}

		[Authorize(Roles = "Coordinator")]
		[HttpGet, Route("coordinator/update-profile")]
		public ActionResult UpdateProfile(string userid)
		{
			Coordinator currentCoordinator = this.GetLoggedInUser() as Coordinator;
			CoordinatorProfileEditModel model = new CoordinatorProfileEditModel();
			if (currentCoordinator != null && currentCoordinator.LoginIdentityID == userid)
			{
				model = _mapper.Map<Coordinator, CoordinatorProfileEditModel>(currentCoordinator);
				model.KeywordList = _commonServices.GetKeywordList();
				model.SelectedKeywords = _commonServices.GetUserSelectedKeywordsByUserID(currentCoordinator.ID);
			}
			return View(model);
		}

		[Authorize(Roles = "Coordinator")]
		[HttpPost, Route("coordinator/update-profile")]
		public ActionResult UpdateProfile(CoordinatorProfileEditModel model)
		{
			Coordinator currentCoordinator = this.GetLoggedInUser() as Coordinator;
			if (currentCoordinator != null && ModelState.IsValid)
			{
				currentCoordinator = _mapper.Map(model, currentCoordinator);
				_commonServices.UpdateProfile(currentCoordinator, model.SelectedKeywordIDs);
			}
			return RedirectToAction("myaccount");
		}

		#endregion

		#region Term

		[HttpGet, Route("coordinator/manage-semester")]
		public ActionResult ManageSemester()
		{
			Coordinator currentCoordinator = this.GetLoggedInUser() as Coordinator;
			if (currentCoordinator != null)
				return RedirectToAction("Index", "Terms", new { userId = currentCoordinator.ID });
			return View();
		}

		#endregion

		#region Keywords

		[HttpGet, Route("coordinator/manage-keywords")]
		public ActionResult ManageKeywords()
		{
			Coordinator currentCoordinator = this.GetLoggedInUser() as Coordinator;
			if (currentCoordinator != null)
				return RedirectToAction("Index", "Keywords", new { userId = currentCoordinator.ID });
			return View();
		}

		#endregion

		#region Statistics

		[Authorize(Roles = "Coordinator")]
		[HttpGet, Route("coordinator/students-requests")]
		public ActionResult StudentsRequests()
		{
			ViewBag.TypeOfUser = "Coordinator";
			Coordinator currentCoordinator = this.GetLoggedInUser() as Coordinator;
			Term currentTerm = _commonServices.GetCurrentOpenTerm();
			if (currentTerm == null)
				return RedirectToAction("manage-semester");
			List<RequestsViewModel> vm = _dbData.GetStudentsRequestsList(currentTerm.ID);

			return View(vm);
		}

		#endregion

		#region Pick up

		[HttpGet, Route("coordinator/posted-by-students")]
		public ActionResult PostedByStudents()
		{
			return RedirectToAction("posted-by-students", "projects");
		}

		#endregion

		#region Remove supervisor

		[HttpGet, Route("coordinator/remove-supervisor")]
		public ActionResult RemoveSupervisor(int? projectID)
		{
			ViewBag.TypeOfUser = "Coordinator";
			if (projectID == null)
				return View();
			ViewBag.ProjectID = projectID;
			ProjectViewModel model = _projectServices.MapperProjectToViewModel((int)projectID);
			if (model == null)
				return View();
			return View(model);
		}

		[HttpGet, Route("coordinator/confirm-to-remove-supervisor")]
		public ActionResult ConfirmRemoveSupervisor(int supervisorID, int projectID)
		{
			ViewBag.TypeOfUser = "Coordinator";

			_projectServices.RemoveSupervisor(supervisorID, projectID);
	    ViewBag.Keyword = projectID;
			return RedirectToAction("remove-supervisor", "coordinator", new { projectID = projectID });
		}

		#endregion

		#region Grade group

		[HttpGet, Route("coordinator/grade-group")]
		public ActionResult GradeGroup(int? groupID)
		{
			ViewBag.TypeOfUser = "Coordinator";
			if (groupID == null)
				return View();
			ViewBag.GroupID = groupID;
			GradeGroupViewModel model = _projectServices.MapperGradeGroupToViewModel((int)groupID);
			if (model == null)
				return View();
			ViewBag.Comments = model.Comments;
			model.Comments = "";
			return View(model);
		}

		[HttpPost, Route("coordinator/confirm-to-grade-group")]
		public ActionResult ConfirmGradeGroup(GradeGroupViewModel model)
		{
			ViewBag.TypeOfUser = "Coordinator";
			Coordinator currentCoordinator = this.GetLoggedInUser() as Coordinator;
			if (currentCoordinator != null && ModelState.IsValid)
				_projectServices.GradeGroupByCoordinator(currentCoordinator.ID, model);
			ViewBag.Keyword = model.ID;
			return RedirectToAction("grade-group", "coordinator", new { groupID = model.ID });
		}

		#endregion
	}
}

src/SmartRP/Controllers/MyAccountController.cs
using System.Net;
using System.Web.Mvc;
using SmartRP.Domain;
using SmartRP.Infrastructure.Auth;
using RazorEngine.Templating;
using SmartRP.Domain.Service;

namespace SmartRP.Controllers
{
	[Authorize]
	public class MyAccountController : Controller
	{
		#region Fields

		private readonly ILoginService _loginService;
		private readonly IUserService _userService;
		private readonly IProjectService _projectService;

		#endregion

		#region Ctor

		public MyAccountController(ILoginService loginService, IUserService userService, IProjectService projectService)
		{
			_loginService = loginService;
			_userService = userService;
			_projectService = projectService;
		}

		#endregion

		#region Actions

		// GET: MyAccount
		public ActionResult Index()
		{
			string userType = _userService.GetCurrentRole(User.Identity.Name);
			if (userType == "Admin")
				return RedirectToAction("Info", "Manage", new { usertype = userType });
			else
			{
				User user = _userService.GetUserIDByEmail(User.Identity.Name);
				string userID = user.LoginIdentityID;
				if (_userService.IsNewUser(User.Identity.Name))
					return RedirectToAction("Update-Profile", userType, new { userid = userID });
				else
					return RedirectToAction("MyAccount", userType);
			}
		}

		[Authorize(Roles = "Admin")]
		public ActionResult ViewUsers()
		{
			var users = _userService.GetAllUser();
			return View(users);
		}

		// GET: MyAccount/Details/5
		[Authorize(Roles = "Admin")]
		public ActionResult Details(int? id)
		{
			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			User user = _userService.FindUser(id);
			if (user == null)
			{
				return HttpNotFound();
			}
			return View(user);
		}

		#endregion
	}
}

src/SmartRP/Controllers/ProjectsController.cs
using System.Web.Mvc;
using SmartRP.Domain;
using SmartRP.Infrastructure.Data;
using SmartRP.Domain.Service;
using AutoMapper;
using System;
using System.Collections.Generic;
using PagedList;
using System.Linq;

namespace SmartRP.Controllers
{
	[Authorize]
	public class ProjectsController : Controller
	{

		#region Fields

		private readonly ICommonService _commonServices;
		private readonly IProjectService _projectServices;
		private readonly IUserService _userServices;
		private readonly IUploadService _uploadServices;
		private readonly DbData _dbData;
		private readonly IMapper _mapper;
		private const int PageSize = 10;

		#endregion

		#region Ctor

		public ProjectsController(ICommonService commonServices, IProjectService projectServices, IUserService userServices, IUploadService uploadServices, DbData dbData, IMapper mapper)
		{
			_commonServices = commonServices;
			_projectServices = projectServices;
			_userServices = userServices;
			_uploadServices = uploadServices;
			_dbData = dbData;
			_mapper = mapper;
		}

		#endregion

		#region ProjectPool

		[Authorize(Roles = "Supervisor, CoSupervisor, ExternalSupervisor")]
		[HttpGet, Route("projects/my-project-pool")]
		public ActionResult MyProjectsInPool()
		{
			string userType = _userServices.GetCurrentRole(User.Identity.Name);
			ViewBag.TypeOfUser = userType;
			List<ProjectPoolEditModel> projectPoolsVM = getMyProjectPoolVMList(userType);

			return View(projectPoolsVM);
		}

		[Authorize(Roles = "Supervisor, CoSupervisor, ExternalSupervisor")]
		[HttpGet, Route("projects/add-project-to-pool")]
		public ActionResult AddProjectToPool()
		{
			string userType = _userServices.GetCurrentRole(User.Identity.Name);
			ViewBag.TypeOfUser = userType;
			User user = _userServices.GetUserIDByEmail(User.Identity.Name);
			ProjectPool projectPool = new ProjectPool(user.ID);
			ProjectPoolEditModel model = _mapper.Map<ProjectPool, ProjectPoolEditModel>(projectPool);
			ViewBag.PathUpload = Url.Action("UploadFileToServer", "Upload", new { fileString = "ProjectPool", subjectAndUserID = "userID-" + user.ID });
            ViewBag.PathDelete = Url.Action("DeleteFileFromServer", "Upload");

			return View(model);
		}

		[HttpPost, Route("projects/add-project-to-pool")]
		public ActionResult AddProjectToPool(ProjectPoolEditModel model)
		{
			string userType = _userServices.GetCurrentRole(User.Identity.Name);
			User user = _userServices.GetUserIDByEmail(User.Identity.Name);

			if (user != null && ModelState.IsValid)
			{
				if (!_projectServices.AddProjectToPool(userType, user.ID, model))
					return RedirectToAction("ErrorAlert", "Error", new { errorTitle = "post projectPool error !", errorContent = "Can not post a projectPool in the subject !" });
			}
			else
				return RedirectToAction("ErrorAlert", "Error", new { errorTitle = "post projectPool model error !", errorContent = "Can not post a projectPool in the subject !" });

			return RedirectToAction("my-project-pool");
		}


		[Authorize(Roles = "Supervisor, CoSupervisor, ExternalSupervisor")]
		[HttpGet, Route("projects/update-project-of-pool")]
		public ActionResult UpdateProjectOfPool(int projectID)
		{
			string userType = _userServices.GetCurrentRole(User.Identity.Name);
			ViewBag.TypeOfUser = userType;
			User user = _userServices.GetUserIDByEmail(User.Identity.Name);
			ProjectPool projectPool = getProjectPoolByProjectID(userType, projectID);
			if (projectPool == null)
				return RedirectToAction("my-project-pool");
			ProjectPoolEditModel model = _mapper.Map<ProjectPool, ProjectPoolEditModel>(projectPool);
			ViewBag.PathUpload = Url.Action("UploadFileToServer", "Upload", new { fileString = "ProjectPool", subjectAndUserID =  "userID-" + user.ID });
            ViewBag.PathDelete = Url.Action("DeleteFileFromServer", "Upload");
			return View(model);
		}


		[HttpPost, Route("projects/update-project-of-pool")]
		public ActionResult UpdateProjectOfPool(ProjectPoolEditModel model)
		{
			string userType = _userServices.GetCurrentRole(User.Identity.Name);
			ViewBag.TypeOfUser = userType;
			User user = _userServices.GetUserIDByEmail(User.Identity.Name);

			if (user != null && ModelState.IsValid)
			{
				if (!_projectServices.UpdateProjectOfPool(userType, user.ID, model))
					return RedirectToAction("ErrorAlert", "Error", new { errorTitle = "update projectPool error !", errorContent = "Can not update current projectPool!" });
			}
			else
				return RedirectToAction("ErrorAlert", "Error", new { errorTitle = "update projectPool model error !", errorContent = "Can not update a projectPool in the subject !" });

			return RedirectToAction("my-project-pool");
		}

		[HttpGet]
		[Authorize(Roles = "Supervisor, CoSupervisor, ExternalSupervisor")]
		public ActionResult DeleteProjectInPool(int? projectID)
		{
			string userType = _userServices.GetCurrentRole(User.Identity.Name);
			ViewBag.TypeOfUser = userType;

			ProjectPool projectPool = getProjectPoolByProjectID(userType, (int)projectID);
			if (projectPool == null)
				return RedirectToAction("my-project-pool");

			var model = _mapper.Map<ProjectPool, ProjectPoolEditModel>(projectPool);
			return View(model);
		}

		// POST: 
		[HttpPost, ActionName("DeleteProjectInPool")]
		[ValidateAntiForgeryToken]
		public ActionResult DeletePoolProjectConfirmed(int projectID)
		{
			string userType = _userServices.GetCurrentRole(User.Identity.Name);
			ViewBag.TypeOfUser = userType;
			User user = _userServices.GetUserIDByEmail(User.Identity.Name);

			if (user != null && ModelState.IsValid)
				_projectServices.DeletePostedProjectPool(userType, user.ID, projectID);
			return RedirectToAction("my-project-pool");
		}

		#endregion

		#region Publish - PoolProject to Project

		[HttpGet, Route("projects/publish-project")]
		[Authorize(Roles = "Supervisor, CoSupervisor, ExternalSupervisor")]
		public ActionResult PublishProject(int projectID)
		{
			//the projectID is the projectPoolID
			Term currentTerm = _commonServices.GetCurrentOpenTerm();
			if (currentTerm == null)
				return RedirectToAction("ErrorAlert", "Error", new { errorTitle = "Semester not open!", errorContent = "Can not find current open semester !" });
			string userType = _userServices.GetCurrentRole(User.Identity.Name);
			User user = _userServices.GetUserIDByEmail(User.Identity.Name);
			ViewBag.TypeOfUser = userType;
			ProjectPool projectPool = getProjectPoolByProjectID(userType, projectID);
			if (projectPool == null)
				return RedirectToAction("my-project-pool");
			Project project = _mapper.Map<ProjectPool, Project>(projectPool);
			project.ID = 0;
			project.ExpiredAt = currentTerm.EndAt;
			project.PublisherType = userType;
			project.Status = ProjectStatus.Opening;
			ProjectEditModel model = _projectServices.MapperProjectToEditModel(project, user.ID, userType);
			Subject subject = getUserRegisteredCurrentSubject(userType);

			///may need add: copy document from \projectpool to \project and change DocumentURL
			ViewBag.PathUpload = Url.Action("UploadFileToServer", "Upload", new { fileString = "Project", subjectAndUserID = "userID-" + user.ID });
            ViewBag.PathDelete = Url.Action("DeleteFileFromServer", "Upload");

			return View(model);
		}

		[HttpPost, Route("projects/publish-project")]
		public ActionResult PublishProject(ProjectEditModel model)
		{
			string userType = _userServices.GetCurrentRole(User.Identity.Name);
			User user = _userServices.GetUserIDByEmail(User.Identity.Name);
			ViewBag.TypeOfUser = userType;
			if (ModelState.IsValid)
			{
				Project project = user.GetProjects().Where(p => p.Title == model.Title && p.SubjectID == model.SubjectID).FirstOrDefault();
				if (project != null)
					return RedirectToAction("ErrorAlert", "Error", new { errorTitle = "Publish project error !", errorContent = "Can not publish two projects with the same title during the same subject !" });

				if (!_projectServices.AddPostedProject(userType, user.ID, model))
					return RedirectToAction("ErrorAlert", "Error", new { errorTitle = "Publish project error !", errorContent = "Can not publish this project in the subject !" });
			}
			else
				return RedirectToAction("ErrorAlert", "Error", new { errorTitle = "Publish project model state error !", errorContent = "Can not post a project in the subject !" });

			return RedirectToAction("my-published-project");
		}

		#endregion

		#region List  

		[HttpGet, Route("projects/my-published-project")]
		public ActionResult MyPublishedProject()
		{
			string userType = _userServices.GetCurrentRole(User.Identity.Name);
			User user = _userServices.GetUserIDByEmail(User.Identity.Name);
			ViewBag.TypeOfUser = userType;
			List<ProjectViewModel> projectsVM = getMyProjectVMList(userType);

			return View(projectsVM);
		}

		[Authorize(Roles = "Student, Supervisor, CoSupervisor, Coordinator")]
		[HttpGet, Route("projects/project-list")]
		public ActionResult ProjectsList(int? subjectID, string sortOrder, string currentFilter, string searchString, int? page)
		{
			string userType = _userServices.GetCurrentRole(User.Identity.Name);

			ViewBag.CurrentSort = sortOrder;
			ViewBag.TitleSortParm = String.IsNullOrEmpty(sortOrder) ? "title_desc" : "";
			ViewBag.StatusSortParm = sortOrder == "status" ? "statusdesc" : "status";
			ViewBag.IDSortParm = sortOrder == "id" ? "iddesc" : "id";
			if (searchString != null)
				page = 1;
			else
				searchString = currentFilter;

			ViewBag.CurrentFilter = searchString;
			int pageIndex = 1;
			pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;
			IEnumerable<Project> projects;
			if (userType == "Supervisor" || userType == "Coordinator")
			{
				projects = _projectServices.GetCurrentSemesterProjectList();
			}
			else if (userType == "CoSupervisor")
			{
				CoSupervisor currentCoSupervisor = this.GetLoggedInUser() as CoSupervisor;
				projects = _projectServices.GetCurrentEnrolledSemesterByCoSupervisorProjectList(currentCoSupervisor.ID);
			}
			else
			{
				if (subjectID == null)

src/SmartRP/Views/Coordinator/CoordinatorMenu.cshtml
<div class="nav nav-sidebar">
	@Html.ActionLink(" Project List", "project-list","Projects", routeValues: null, htmlAttributes: new { title = "All public project list", @class = "btn btn-block btn-success btn-lg fa fa-cubes" })
	@Html.ActionLink(" Student Status", "current-status", "Student", routeValues: null, htmlAttributes: new { title = "Student have not enjoy project group list", @class = "btn btn-block btn-success btn-lg fa fa-list" })
	@Html.ActionLink(" Student Requests", "students-requests", "Coordinator", routeValues: null, htmlAttributes: new { title = "Student Requests list", @class = "btn btn-block btn-info btn-lg fa fa-users" })

	<hr />

	@Html.ActionLink(" Manage Keyword", "manage-keywords", "Coordinator", routeValues: null, htmlAttributes: new { title = "Keyword Management", @class = "btn btn-block btn-warning btn-lg fa fa-font" })
	@Html.ActionLink(" Manage Semester", "manage-semester", "Coordinator", routeValues: null, htmlAttributes: new { title = "Semester (Term) Management", @class = "btn btn-block btn-warning btn-lg fa fa-calendar" })
	@Html.ActionLink(" Grade Group", "grade-group", "Coordinator", routeValues: null, htmlAttributes: new { title = "Grade Group", @class = "btn btn-block btn-danger btn-lg fa fa-graduation-cap" })

	@Html.ActionLink(" Remove Supervisor", "remove-supervisor", "Coordinator", routeValues: null, htmlAttributes: new { title = "Manage Projects", @class = "btn btn-block btn-danger btn-lg fa fa-cube" })
</div>

src/SmartRP/Views/Coordinator/MyAccount.cshtml
@model SmartRP.Domain.CoordinatorViewModel

@{
	ViewBag.Title = "Coordinator Profile";
}
<style>
	dt, dd {
		padding-bottom: 2px;
	}
</style>
<script type="text/javascript">
	$(window).on('load', function () {
		$(".loadering").fadeOut("slow");
	})
</script>
<div class="loadering"></div>

<div class="container-fluid">
	<div class="row">
		<div class="col-sm-3 col-md-2 sidebar">
			<br />
			<h4>@Model.UserType</h4>
			@Html.Action("Menu", @Model.UserType)
		</div>
		<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
			<p class="bg-light" style="padding-top:8px;">
				&nbsp; <span class="glyphicon glyphicon-home"></span>
				&nbsp; <span class="fa fa-angle-right"></span>&nbsp;
				@Html.ActionLink(" My profile", "myaccount", (string)@ViewBag.TypeOfUser, null, null)
			</p>
			<hr />
			<p>
				@Html.ActionLink(" Edit profile", "Update-Profile", new { userid = Model.UserID }, new { @class = "btn btn-warning btn-sm fa fa-pencil-square-o" })
			</p>
			<dl class="dl-horizontal">
				<dt>
					@Html.DisplayNameFor(model => model.Firstname)
				</dt>

				<dd>
					@Html.DisplayFor(model => model.Firstname)
				</dd>

				<dt>
					@Html.DisplayNameFor(model => model.Lastname)
				</dt>

				<dd>
					@Html.DisplayFor(model => model.Lastname)
				</dd>

				<dt>
					@Html.DisplayNameFor(model => model.Email)
				</dt>

				<dd>
					@Html.DisplayFor(model => model.Email)
				</dd>

				<dt>
					@Html.DisplayNameFor(model => model.Phone)
				</dt>

				<dd>
					@Html.DisplayFor(model => model.Phone)
				</dd>
				<dt>
					@Html.DisplayNameFor(model => model.CreatedAt)
				</dt>

				<dd>
					@Html.DisplayFor(model => model.CreatedAt)
				</dd>

				<dt>
					@Html.DisplayNameFor(model => model.UpdatedAt)
				</dt>

				<dd>
					@Html.DisplayFor(model => model.UpdatedAt)
				</dd>

				<dt>
					@Html.DisplayNameFor(model => model.UserSelectedKeywords)
				</dt>

				<dd>
					<div class="alert alert-warning" role="alert" style="overflow:auto; max-height:100px">
						@foreach (var item in Model.UserSelectedKeywords)
						{
					    	@Html.DisplayFor(model => item.Title)<span>, </span>
						}
					</div>

				</dd>
			</dl>

		</div>
	</div>
</div>

src/SmartRP/Views/Coordinator/Profile.cshtml
@model SmartRP.Domain.CoordinatorViewModel

@{
	ViewBag.Title = "Profile";
}
<style>
	dt, dd {
		padding-bottom: 2px;
	}
</style>
<div class="container-fluid">
	<div class="row">
		<div class="col-sm-3 col-md-2 sidebar">
			<br />
			<h4>@ViewBag.TypeOfUser</h4>

			@Html.Action("Menu", (string)@ViewBag.TypeOfUser)
		</div>
		<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
			<h3>Co-ordinator  #@Model.ID  profile</h3>
			<hr />

			<dl class="dl-horizontal">
				<dt>
					@Html.DisplayNameFor(model => model.Firstname)
				</dt>

				<dd>
					@Html.DisplayFor(model => model.Firstname)
				</dd>

				<dt>
					@Html.DisplayNameFor(model => model.Lastname)
				</dt>

				<dd>
					@Html.DisplayFor(model => model.Lastname)
				</dd>

				<dt>
					@Html.DisplayNameFor(model => model.Email)
				</dt>

				<dd>
					<a href="mailto:@Html.DisplayFor(model => model.Email)">@Html.DisplayFor(model => model.Email)</a>
				</dd>

				<dt>
					@Html.DisplayNameFor(model => model.Phone)
				</dt>

				<dd>
					<a href="tel:@Html.DisplayFor(model => model.Phone)">@Html.DisplayFor(model => model.Phone)</a>
				</dd>


				<dt>
					@Html.DisplayNameFor(model => model.UserSelectedKeywords)
				</dt>

				<dd>
					<div class="alert alert-warning" role="alert" style="overflow:auto; max-height:100px">
						@foreach (var item in Model.UserSelectedKeywords)
		      	{
		        	@Html.DisplayFor(model => item.Title)<span>, </span>
						}
					</div>
				</dd>
			</dl>

			<hr />
			<button onclick="self.close()" class="btn btn-default">Close this window</button>
			@*<button onclick="goBack()" class="btn btn-default">Go Back</button>
			<script>
				function goBack() {
					window.history.back();
				}
			</script>*@
		</div>

	</div>
</div>

src/SmartRP/Views/Coordinator/StudentsRequests.cshtml
@model IEnumerable<SmartRP.Domain.RequestsViewModel>

@{
	ViewBag.Title = "Students Requests";
}

<div class="container-fluid">
	<div class="row">
		<div class="col-sm-3 col-md-2 sidebar">
			<br />
			<h4>@ViewBag.TypeOfUser</h4>
			@Html.Action("Menu", (string)@ViewBag.TypeOfUser)
		</div>
		<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
			<p class="bg-light" style="padding-top:8px;">
				&nbsp; <span class="glyphicon glyphicon-home"></span>
				&nbsp; <span class="fa fa-angle-right"></span>&nbsp;
				@Html.ActionLink(" Student Requests", "students-requests", (string)@ViewBag.TypeOfUser, null, null)
			</p>
 
			<div class="alert alert-success alert-dismissable fade in">
				<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
				<strong>Information: </strong>The student has sent a request but proposer has not responded.
			</div>
			@using (Html.BeginForm("students-requests", "coordinator", FormMethod.Get))
			{

			<table class="table table-striped">
				<tr>
					<th>
						ID
					</th>
					<th>
						Project Title
					</th>
					<th>
						Group Size
					</th>
					<th>
					 Proposer
					</th>
					<th>
						Proposer's Email
					</th>
					<th>
						Student
					</th>
				</tr>

				@foreach (var item in Model)
				{
				<tr>
					<td>
						<span>#</span>@Html.DisplayFor(modelItem => item.ID)
					</td>
					<td>
						@Html.ActionLink(@item.Title, "Details", "Projects", new { projectID = item.ID }, new { title = "Look Details" , target = "_blank" })
					</td>

					<td>
						@Html.DisplayFor(modelItem => item.JoinedStudents) /
						@Html.DisplayFor(modelItem => item.GroupSize)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.ProposerName)

					</td>
					<td>
 
						<a href="mailto:@Html.DisplayFor(modelItem => item.Email)">@Html.DisplayFor(modelItem => item.Email)</a>
					</td>
					<td>
						@Html.ActionLink("Student " + item.StudentID, "Profile", "Student", new { id = item.StudentID }, htmlAttributes: new { target = "_blank" })
 
					</td>
				</tr>
				}
			</table>
			}
		</div>
	</div>
</div>